export interface CountryPhoneCode {
  id: string
  name: string
  dialingCode: string
}

export const COUNTRY_PHONE_CODES: CountryPhoneCode[] = [
  { id: "AF", name: "Afghanistan", dialingCode: "+93" },
  { id: "AL", name: "Albania", dialingCode: "+355" },
  { id: "DZ", name: "Algeria", dialingCode: "+213" },
  { id: "AS", name: "American Samoa", dialingCode: "+1684" },
  { id: "AD", name: "Andorra", dialingCode: "+376" },
  { id: "AO", name: "Angola", dialingCode: "+244" },
  { id: "AI", name: "Anguilla", dialingCode: "+1264" },
  { id: "AG", name: "Antigua and Barbuda", dialingCode: "+1268" },
  { id: "AR", name: "Argentina", dialingCode: "+54" },
  { id: "AM", name: "Armenia", dialingCode: "+374" },
  { id: "AW", name: "Aruba", dialingCode: "+297" },
  { id: "AU", name: "Australia", dialingCode: "+61" },
  { id: "AT", name: "Austria", dialingCode: "+43" },
  { id: "AZ", name: "Azerbaijan", dialingCode: "+994" },
  { id: "BS", name: "Bahamas", dialingCode: "+1242" },
  { id: "BH", name: "Bahrain", dialingCode: "+973" },
  { id: "BD", name: "Bangladesh", dialingCode: "+880" },
  { id: "BB", name: "Barbados", dialingCode: "+1246" },
  { id: "BY", name: "Belarus", dialingCode: "+375" },
  { id: "BE", name: "Belgium", dialingCode: "+32" },
  { id: "BZ", name: "Belize", dialingCode: "+501" },
  { id: "BJ", name: "Benin", dialingCode: "+229" },
  { id: "BM", name: "Bermuda", dialingCode: "+1441" },
  { id: "BT", name: "Bhutan", dialingCode: "+975" },
  { id: "BO", name: "Bolivia", dialingCode: "+591" },
  { id: "BA", name: "Bosnia and Herzegovina", dialingCode: "+387" },
  { id: "BW", name: "Botswana", dialingCode: "+267" },
  { id: "BR", name: "Brazil", dialingCode: "+55" },
  { id: "BN", name: "Brunei", dialingCode: "+673" },
  { id: "BG", name: "Bulgaria", dialingCode: "+359" },
  { id: "BF", name: "Burkina Faso", dialingCode: "+226" },
  { id: "BI", name: "Burundi", dialingCode: "+257" },
  { id: "KH", name: "Cambodia", dialingCode: "+855" },
  { id: "CM", name: "Cameroon", dialingCode: "+237" },
  { id: "CA", name: "Canada", dialingCode: "+1" },
  { id: "CV", name: "Cape Verde", dialingCode: "+238" },
  { id: "KY", name: "Cayman Islands", dialingCode: "+1345" },
  { id: "CF", name: "Central African Republic", dialingCode: "+236" },
  { id: "TD", name: "Chad", dialingCode: "+235" },
  { id: "CL", name: "Chile", dialingCode: "+56" },
  { id: "CN", name: "China", dialingCode: "+86" },
  { id: "CO", name: "Colombia", dialingCode: "+57" },
  { id: "KM", name: "Comoros", dialingCode: "+269" },
  { id: "CG", name: "Congo", dialingCode: "+242" },
  { id: "CD", name: "Congo (DRC)", dialingCode: "+243" },
  { id: "CR", name: "Costa Rica", dialingCode: "+506" },
  { id: "HR", name: "Croatia", dialingCode: "+385" },
  { id: "CU", name: "Cuba", dialingCode: "+53" },
  { id: "CY", name: "Cyprus", dialingCode: "+357" },
  { id: "CZ", name: "Czech Republic", dialingCode: "+420" },
  { id: "DK", name: "Denmark", dialingCode: "+45" },
  { id: "DJ", name: "Djibouti", dialingCode: "+253" },
  { id: "DM", name: "Dominica", dialingCode: "+1767" },
  { id: "DO", name: "Dominican Republic", dialingCode: "+1849" },
  { id: "EC", name: "Ecuador", dialingCode: "+593" },
  { id: "EG", name: "Egypt", dialingCode: "+20" },
  { id: "SV", name: "El Salvador", dialingCode: "+503" },
  { id: "GQ", name: "Equatorial Guinea", dialingCode: "+240" },
  { id: "ER", name: "Eritrea", dialingCode: "+291" },
  { id: "EE", name: "Estonia", dialingCode: "+372" },
  { id: "ET", name: "Ethiopia", dialingCode: "+251" },
  { id: "FJ", name: "Fiji", dialingCode: "+679" },
  { id: "FI", name: "Finland", dialingCode: "+358" },
  { id: "FR", name: "France", dialingCode: "+33" },
  { id: "GA", name: "Gabon", dialingCode: "+241" },
  { id: "GM", name: "Gambia", dialingCode: "+220" },
  { id: "GE", name: "Georgia", dialingCode: "+995" },
  { id: "DE", name: "Germany", dialingCode: "+49" },
  { id: "GH", name: "Ghana", dialingCode: "+233" },
  { id: "GR", name: "Greece", dialingCode: "+30" },
  { id: "GD", name: "Grenada", dialingCode: "+1473" },
  { id: "GT", name: "Guatemala", dialingCode: "+502" },
  { id: "GN", name: "Guinea", dialingCode: "+224" },
  { id: "GW", name: "Guinea-Bissau", dialingCode: "+245" },
  { id: "GY", name: "Guyana", dialingCode: "+592" },
  { id: "HT", name: "Haiti", dialingCode: "+509" },
  { id: "HN", name: "Honduras", dialingCode: "+504" },
  { id: "HK", name: "Hong Kong", dialingCode: "+852" },
  { id: "HU", name: "Hungary", dialingCode: "+36" },
  { id: "IS", name: "Iceland", dialingCode: "+354" },
  { id: "IN", name: "India", dialingCode: "+91" },
  { id: "ID", name: "Indonesia", dialingCode: "+62" },
  { id: "IR", name: "Iran", dialingCode: "+98" },
  { id: "IQ", name: "Iraq", dialingCode: "+964" },
  { id: "IE", name: "Ireland", dialingCode: "+353" },
  { id: "IL", name: "Israel", dialingCode: "+972" },
  { id: "IT", name: "Italy", dialingCode: "+39" },
  { id: "CI", name: "Ivory Coast", dialingCode: "+225" },
  { id: "JM", name: "Jamaica", dialingCode: "+1876" },
  { id: "JP", name: "Japan", dialingCode: "+81" },
  { id: "JO", name: "Jordan", dialingCode: "+962" },
  { id: "KZ", name: "Kazakhstan", dialingCode: "+7" },
  { id: "KE", name: "Kenya", dialingCode: "+254" },
  { id: "KI", name: "Kiribati", dialingCode: "+686" },
  { id: "KW", name: "Kuwait", dialingCode: "+965" },
  { id: "KG", name: "Kyrgyzstan", dialingCode: "+996" },
  { id: "LA", name: "Laos", dialingCode: "+856" },
  { id: "LV", name: "Latvia", dialingCode: "+371" },
  { id: "LB", name: "Lebanon", dialingCode: "+961" },
  { id: "LS", name: "Lesotho", dialingCode: "+266" },
  { id: "LR", name: "Liberia", dialingCode: "+231" },
  { id: "LY", name: "Libya", dialingCode: "+218" },
  { id: "LI", name: "Liechtenstein", dialingCode: "+423" },
  { id: "LT", name: "Lithuania", dialingCode: "+370" },
  { id: "LU", name: "Luxembourg", dialingCode: "+352" },
  { id: "MO", name: "Macau", dialingCode: "+853" },
  { id: "MG", name: "Madagascar", dialingCode: "+261" },
  { id: "MW", name: "Malawi", dialingCode: "+265" },
  { id: "MY", name: "Malaysia", dialingCode: "+60" },
  { id: "MV", name: "Maldives", dialingCode: "+960" },
  { id: "ML", name: "Mali", dialingCode: "+223" },
  { id: "MT", name: "Malta", dialingCode: "+356" },
  { id: "MR", name: "Mauritania", dialingCode: "+222" },
  { id: "MU", name: "Mauritius", dialingCode: "+230" },
  { id: "MX", name: "Mexico", dialingCode: "+52" },
  { id: "MD", name: "Moldova", dialingCode: "+373" },
  { id: "MC", name: "Monaco", dialingCode: "+377" },
  { id: "MN", name: "Mongolia", dialingCode: "+976" },
  { id: "ME", name: "Montenegro", dialingCode: "+382" },
  { id: "MA", name: "Morocco", dialingCode: "+212" },
  { id: "MZ", name: "Mozambique", dialingCode: "+258" },
  { id: "MM", name: "Myanmar", dialingCode: "+95" },
  { id: "NA", name: "Namibia", dialingCode: "+264" },
  { id: "NP", name: "Nepal", dialingCode: "+977" },
  { id: "NL", name: "Netherlands", dialingCode: "+31" },
  { id: "NZ", name: "New Zealand", dialingCode: "+64" },
  { id: "NI", name: "Nicaragua", dialingCode: "+505" },
  { id: "NE", name: "Niger", dialingCode: "+227" },
  { id: "NG", name: "Nigeria", dialingCode: "+234" },
  { id: "KP", name: "North Korea", dialingCode: "+850" },
  { id: "MK", name: "North Macedonia", dialingCode: "+389" },
  { id: "NO", name: "Norway", dialingCode: "+47" },
  { id: "NO", name: "Norway", dialingCode: "+47" },
  { id: "OM", name: "Oman", dialingCode: "+968" },
  { id: "PK", name: "Pakistan", dialingCode: "+92" },
  { id: "PS", name: "Palestine", dialingCode: "+970" },
  { id: "PA", name: "Panama", dialingCode: "+507" },
  { id: "PG", name: "Papua New Guinea", dialingCode: "+675" },
  { id: "PY", name: "Paraguay", dialingCode: "+595" },
  { id: "PE", name: "Peru", dialingCode: "+51" },
  { id: "PH", name: "Philippines", dialingCode: "+63" },
  { id: "PL", name: "Poland", dialingCode: "+48" },
  { id: "PT", name: "Portugal", dialingCode: "+351" },
  { id: "PR", name: "Puerto Rico", dialingCode: "+1939" },
  { id: "QA", name: "Qatar", dialingCode: "+974" },
  { id: "RO", name: "Romania", dialingCode: "+40" },
  { id: "RU", name: "Russia", dialingCode: "+7" },
  { id: "RW", name: "Rwanda", dialingCode: "+250" },
  { id: "KN", name: "Saint Kitts and Nevis", dialingCode: "+1869" },
  { id: "LC", name: "Saint Lucia", dialingCode: "+1758" },
  { id: "VC", name: "Saint Vincent", dialingCode: "+1784" },
  { id: "WS", name: "Samoa", dialingCode: "+685" },
  { id: "SA", name: "Saudi Arabia", dialingCode: "+966" },
  { id: "SN", name: "Senegal", dialingCode: "+221" },
  { id: "RS", name: "Serbia", dialingCode: "+381" },
  { id: "SC", name: "Seychelles", dialingCode: "+248" },
  { id: "SL", name: "Sierra Leone", dialingCode: "+232" },
  { id: "SG", name: "Singapore", dialingCode: "+65" },
  { id: "SK", name: "Slovakia", dialingCode: "+421" },
  { id: "SI", name: "Slovenia", dialingCode: "+386" },
  { id: "SB", name: "Solomon Islands", dialingCode: "+677" },
  { id: "SO", name: "Somalia", dialingCode: "+252" },
  { id: "ZA", name: "South Africa", dialingCode: "+27" },
  { id: "KR", name: "South Korea", dialingCode: "+82" },
  { id: "SS", name: "South Sudan", dialingCode: "+211" },
  { id: "ES", name: "Spain", dialingCode: "+34" },
  { id: "LK", name: "Sri Lanka", dialingCode: "+94" },
  { id: "SD", name: "Sudan", dialingCode: "+249" },
  { id: "SR", name: "Suriname", dialingCode: "+597" },
  { id: "SE", name: "Sweden", dialingCode: "+46" },
  { id: "CH", name: "Switzerland", dialingCode: "+41" },
  { id: "SY", name: "Syria", dialingCode: "+963" },
  { id: "TW", name: "Taiwan", dialingCode: "+886" },
  { id: "TJ", name: "Tajikistan", dialingCode: "+992" },
  { id: "TZ", name: "Tanzania", dialingCode: "+255" },
  { id: "TH", name: "Thailand", dialingCode: "+66" },
  { id: "TG", name: "Togo", dialingCode: "+228" },
  { id: "TO", name: "Tonga", dialingCode: "+676" },
  { id: "TT", name: "Trinidad and Tobago", dialingCode: "+1868" },
  { id: "TN", name: "Tunisia", dialingCode: "+216" },
  { id: "TR", name: "Turkey", dialingCode: "+90" },
  { id: "TM", name: "Turkmenistan", dialingCode: "+993" },
  { id: "UG", name: "Uganda", dialingCode: "+256" },
  { id: "UA", name: "Ukraine", dialingCode: "+380" },
  { id: "AE", name: "United Arab Emirates", dialingCode: "+971" },
  { id: "GB", name: "United Kingdom", dialingCode: "+44" },
  { id: "US", name: "United States", dialingCode: "+1" },
  { id: "UY", name: "Uruguay", dialingCode: "+598" },
  { id: "UZ", name: "Uzbekistan", dialingCode: "+998" },
  { id: "VU", name: "Vanuatu", dialingCode: "+678" },
  { id: "VE", name: "Venezuela", dialingCode: "+58" },
  { id: "VN", name: "Vietnam", dialingCode: "+84" },
  { id: "YE", name: "Yemen", dialingCode: "+967" },
  { id: "ZM", name: "Zambia", dialingCode: "+260" },
  { id: "ZW", name: "Zimbabwe", dialingCode: "+263" },
]

export const DEFAULT_COUNTRY_PHONE_CODE: CountryPhoneCode = COUNTRY_PHONE_CODES.find((c) => c.id === "NO") ?? COUNTRY_PHONE_CODES[0]
