//
//  CountryPhoneCode.swift
//  SOCIETY
//
//  Full list of country dialing codes with flag emojis.
//

import Foundation

struct CountryPhoneCode: Identifiable, Hashable {
    let id: String        // ISO 3166-1 alpha-2 code (e.g. "NO")
    let name: String      // Country name
    let flag: String      // Flag emoji
    let dialingCode: String // E.g. "+47"

    /// Norway as the default country.
    static let norway = CountryPhoneCode(id: "NO", name: "Norway", flag: "🇳🇴", dialingCode: "+47")

    /// Full list of countries sorted alphabetically by name.
    static let all: [CountryPhoneCode] = [
        CountryPhoneCode(id: "AF", name: "Afghanistan", flag: "🇦🇫", dialingCode: "+93"),
        CountryPhoneCode(id: "AL", name: "Albania", flag: "🇦🇱", dialingCode: "+355"),
        CountryPhoneCode(id: "DZ", name: "Algeria", flag: "🇩🇿", dialingCode: "+213"),
        CountryPhoneCode(id: "AS", name: "American Samoa", flag: "🇦🇸", dialingCode: "+1684"),
        CountryPhoneCode(id: "AD", name: "Andorra", flag: "🇦🇩", dialingCode: "+376"),
        CountryPhoneCode(id: "AO", name: "Angola", flag: "🇦🇴", dialingCode: "+244"),
        CountryPhoneCode(id: "AI", name: "Anguilla", flag: "🇦🇮", dialingCode: "+1264"),
        CountryPhoneCode(id: "AG", name: "Antigua and Barbuda", flag: "🇦🇬", dialingCode: "+1268"),
        CountryPhoneCode(id: "AR", name: "Argentina", flag: "🇦🇷", dialingCode: "+54"),
        CountryPhoneCode(id: "AM", name: "Armenia", flag: "🇦🇲", dialingCode: "+374"),
        CountryPhoneCode(id: "AW", name: "Aruba", flag: "🇦🇼", dialingCode: "+297"),
        CountryPhoneCode(id: "AU", name: "Australia", flag: "🇦🇺", dialingCode: "+61"),
        CountryPhoneCode(id: "AT", name: "Austria", flag: "🇦🇹", dialingCode: "+43"),
        CountryPhoneCode(id: "AZ", name: "Azerbaijan", flag: "🇦🇿", dialingCode: "+994"),
        CountryPhoneCode(id: "BS", name: "Bahamas", flag: "🇧🇸", dialingCode: "+1242"),
        CountryPhoneCode(id: "BH", name: "Bahrain", flag: "🇧🇭", dialingCode: "+973"),
        CountryPhoneCode(id: "BD", name: "Bangladesh", flag: "🇧🇩", dialingCode: "+880"),
        CountryPhoneCode(id: "BB", name: "Barbados", flag: "🇧🇧", dialingCode: "+1246"),
        CountryPhoneCode(id: "BY", name: "Belarus", flag: "🇧🇾", dialingCode: "+375"),
        CountryPhoneCode(id: "BE", name: "Belgium", flag: "🇧🇪", dialingCode: "+32"),
        CountryPhoneCode(id: "BZ", name: "Belize", flag: "🇧🇿", dialingCode: "+501"),
        CountryPhoneCode(id: "BJ", name: "Benin", flag: "🇧🇯", dialingCode: "+229"),
        CountryPhoneCode(id: "BM", name: "Bermuda", flag: "🇧🇲", dialingCode: "+1441"),
        CountryPhoneCode(id: "BT", name: "Bhutan", flag: "🇧🇹", dialingCode: "+975"),
        CountryPhoneCode(id: "BO", name: "Bolivia", flag: "🇧🇴", dialingCode: "+591"),
        CountryPhoneCode(id: "BA", name: "Bosnia and Herzegovina", flag: "🇧🇦", dialingCode: "+387"),
        CountryPhoneCode(id: "BW", name: "Botswana", flag: "🇧🇼", dialingCode: "+267"),
        CountryPhoneCode(id: "BR", name: "Brazil", flag: "🇧🇷", dialingCode: "+55"),
        CountryPhoneCode(id: "BN", name: "Brunei", flag: "🇧🇳", dialingCode: "+673"),
        CountryPhoneCode(id: "BG", name: "Bulgaria", flag: "🇧🇬", dialingCode: "+359"),
        CountryPhoneCode(id: "BF", name: "Burkina Faso", flag: "🇧🇫", dialingCode: "+226"),
        CountryPhoneCode(id: "BI", name: "Burundi", flag: "🇧🇮", dialingCode: "+257"),
        CountryPhoneCode(id: "KH", name: "Cambodia", flag: "🇰🇭", dialingCode: "+855"),
        CountryPhoneCode(id: "CM", name: "Cameroon", flag: "🇨🇲", dialingCode: "+237"),
        CountryPhoneCode(id: "CA", name: "Canada", flag: "🇨🇦", dialingCode: "+1"),
        CountryPhoneCode(id: "CV", name: "Cape Verde", flag: "🇨🇻", dialingCode: "+238"),
        CountryPhoneCode(id: "KY", name: "Cayman Islands", flag: "🇰🇾", dialingCode: "+1345"),
        CountryPhoneCode(id: "CF", name: "Central African Republic", flag: "🇨🇫", dialingCode: "+236"),
        CountryPhoneCode(id: "TD", name: "Chad", flag: "🇹🇩", dialingCode: "+235"),
        CountryPhoneCode(id: "CL", name: "Chile", flag: "🇨🇱", dialingCode: "+56"),
        CountryPhoneCode(id: "CN", name: "China", flag: "🇨🇳", dialingCode: "+86"),
        CountryPhoneCode(id: "CO", name: "Colombia", flag: "🇨🇴", dialingCode: "+57"),
        CountryPhoneCode(id: "KM", name: "Comoros", flag: "🇰🇲", dialingCode: "+269"),
        CountryPhoneCode(id: "CG", name: "Congo", flag: "🇨🇬", dialingCode: "+242"),
        CountryPhoneCode(id: "CD", name: "Congo (DRC)", flag: "🇨🇩", dialingCode: "+243"),
        CountryPhoneCode(id: "CR", name: "Costa Rica", flag: "🇨🇷", dialingCode: "+506"),
        CountryPhoneCode(id: "HR", name: "Croatia", flag: "🇭🇷", dialingCode: "+385"),
        CountryPhoneCode(id: "CU", name: "Cuba", flag: "🇨🇺", dialingCode: "+53"),
        CountryPhoneCode(id: "CY", name: "Cyprus", flag: "🇨🇾", dialingCode: "+357"),
        CountryPhoneCode(id: "CZ", name: "Czech Republic", flag: "🇨🇿", dialingCode: "+420"),
        CountryPhoneCode(id: "DK", name: "Denmark", flag: "🇩🇰", dialingCode: "+45"),
        CountryPhoneCode(id: "DJ", name: "Djibouti", flag: "🇩🇯", dialingCode: "+253"),
        CountryPhoneCode(id: "DM", name: "Dominica", flag: "🇩🇲", dialingCode: "+1767"),
        CountryPhoneCode(id: "DO", name: "Dominican Republic", flag: "🇩🇴", dialingCode: "+1849"),
        CountryPhoneCode(id: "EC", name: "Ecuador", flag: "🇪🇨", dialingCode: "+593"),
        CountryPhoneCode(id: "EG", name: "Egypt", flag: "🇪🇬", dialingCode: "+20"),
        CountryPhoneCode(id: "SV", name: "El Salvador", flag: "🇸🇻", dialingCode: "+503"),
        CountryPhoneCode(id: "GQ", name: "Equatorial Guinea", flag: "🇬🇶", dialingCode: "+240"),
        CountryPhoneCode(id: "ER", name: "Eritrea", flag: "🇪🇷", dialingCode: "+291"),
        CountryPhoneCode(id: "EE", name: "Estonia", flag: "🇪🇪", dialingCode: "+372"),
        CountryPhoneCode(id: "ET", name: "Ethiopia", flag: "🇪🇹", dialingCode: "+251"),
        CountryPhoneCode(id: "FJ", name: "Fiji", flag: "🇫🇯", dialingCode: "+679"),
        CountryPhoneCode(id: "FI", name: "Finland", flag: "🇫🇮", dialingCode: "+358"),
        CountryPhoneCode(id: "FR", name: "France", flag: "🇫🇷", dialingCode: "+33"),
        CountryPhoneCode(id: "GA", name: "Gabon", flag: "🇬🇦", dialingCode: "+241"),
        CountryPhoneCode(id: "GM", name: "Gambia", flag: "🇬🇲", dialingCode: "+220"),
        CountryPhoneCode(id: "GE", name: "Georgia", flag: "🇬🇪", dialingCode: "+995"),
        CountryPhoneCode(id: "DE", name: "Germany", flag: "🇩🇪", dialingCode: "+49"),
        CountryPhoneCode(id: "GH", name: "Ghana", flag: "🇬🇭", dialingCode: "+233"),
        CountryPhoneCode(id: "GR", name: "Greece", flag: "🇬🇷", dialingCode: "+30"),
        CountryPhoneCode(id: "GD", name: "Grenada", flag: "🇬🇩", dialingCode: "+1473"),
        CountryPhoneCode(id: "GT", name: "Guatemala", flag: "🇬🇹", dialingCode: "+502"),
        CountryPhoneCode(id: "GN", name: "Guinea", flag: "🇬🇳", dialingCode: "+224"),
        CountryPhoneCode(id: "GW", name: "Guinea-Bissau", flag: "🇬🇼", dialingCode: "+245"),
        CountryPhoneCode(id: "GY", name: "Guyana", flag: "🇬🇾", dialingCode: "+592"),
        CountryPhoneCode(id: "HT", name: "Haiti", flag: "🇭🇹", dialingCode: "+509"),
        CountryPhoneCode(id: "HN", name: "Honduras", flag: "🇭🇳", dialingCode: "+504"),
        CountryPhoneCode(id: "HK", name: "Hong Kong", flag: "🇭🇰", dialingCode: "+852"),
        CountryPhoneCode(id: "HU", name: "Hungary", flag: "🇭🇺", dialingCode: "+36"),
        CountryPhoneCode(id: "IS", name: "Iceland", flag: "🇮🇸", dialingCode: "+354"),
        CountryPhoneCode(id: "IN", name: "India", flag: "🇮🇳", dialingCode: "+91"),
        CountryPhoneCode(id: "ID", name: "Indonesia", flag: "🇮🇩", dialingCode: "+62"),
        CountryPhoneCode(id: "IR", name: "Iran", flag: "🇮🇷", dialingCode: "+98"),
        CountryPhoneCode(id: "IQ", name: "Iraq", flag: "🇮🇶", dialingCode: "+964"),
        CountryPhoneCode(id: "IE", name: "Ireland", flag: "🇮🇪", dialingCode: "+353"),
        CountryPhoneCode(id: "IL", name: "Israel", flag: "🇮🇱", dialingCode: "+972"),
        CountryPhoneCode(id: "IT", name: "Italy", flag: "🇮🇹", dialingCode: "+39"),
        CountryPhoneCode(id: "CI", name: "Ivory Coast", flag: "🇨🇮", dialingCode: "+225"),
        CountryPhoneCode(id: "JM", name: "Jamaica", flag: "🇯🇲", dialingCode: "+1876"),
        CountryPhoneCode(id: "JP", name: "Japan", flag: "🇯🇵", dialingCode: "+81"),
        CountryPhoneCode(id: "JO", name: "Jordan", flag: "🇯🇴", dialingCode: "+962"),
        CountryPhoneCode(id: "KZ", name: "Kazakhstan", flag: "🇰🇿", dialingCode: "+7"),
        CountryPhoneCode(id: "KE", name: "Kenya", flag: "🇰🇪", dialingCode: "+254"),
        CountryPhoneCode(id: "KI", name: "Kiribati", flag: "🇰🇮", dialingCode: "+686"),
        CountryPhoneCode(id: "KW", name: "Kuwait", flag: "🇰🇼", dialingCode: "+965"),
        CountryPhoneCode(id: "KG", name: "Kyrgyzstan", flag: "🇰🇬", dialingCode: "+996"),
        CountryPhoneCode(id: "LA", name: "Laos", flag: "🇱🇦", dialingCode: "+856"),
        CountryPhoneCode(id: "LV", name: "Latvia", flag: "🇱🇻", dialingCode: "+371"),
        CountryPhoneCode(id: "LB", name: "Lebanon", flag: "🇱🇧", dialingCode: "+961"),
        CountryPhoneCode(id: "LS", name: "Lesotho", flag: "🇱🇸", dialingCode: "+266"),
        CountryPhoneCode(id: "LR", name: "Liberia", flag: "🇱🇷", dialingCode: "+231"),
        CountryPhoneCode(id: "LY", name: "Libya", flag: "🇱🇾", dialingCode: "+218"),
        CountryPhoneCode(id: "LI", name: "Liechtenstein", flag: "🇱🇮", dialingCode: "+423"),
        CountryPhoneCode(id: "LT", name: "Lithuania", flag: "🇱🇹", dialingCode: "+370"),
        CountryPhoneCode(id: "LU", name: "Luxembourg", flag: "🇱🇺", dialingCode: "+352"),
        CountryPhoneCode(id: "MO", name: "Macau", flag: "🇲🇴", dialingCode: "+853"),
        CountryPhoneCode(id: "MK", name: "North Macedonia", flag: "🇲🇰", dialingCode: "+389"),
        CountryPhoneCode(id: "MG", name: "Madagascar", flag: "🇲🇬", dialingCode: "+261"),
        CountryPhoneCode(id: "MW", name: "Malawi", flag: "🇲🇼", dialingCode: "+265"),
        CountryPhoneCode(id: "MY", name: "Malaysia", flag: "🇲🇾", dialingCode: "+60"),
        CountryPhoneCode(id: "MV", name: "Maldives", flag: "🇲🇻", dialingCode: "+960"),
        CountryPhoneCode(id: "ML", name: "Mali", flag: "🇲🇱", dialingCode: "+223"),
        CountryPhoneCode(id: "MT", name: "Malta", flag: "🇲🇹", dialingCode: "+356"),
        CountryPhoneCode(id: "MR", name: "Mauritania", flag: "🇲🇷", dialingCode: "+222"),
        CountryPhoneCode(id: "MU", name: "Mauritius", flag: "🇲🇺", dialingCode: "+230"),
        CountryPhoneCode(id: "MX", name: "Mexico", flag: "🇲🇽", dialingCode: "+52"),
        CountryPhoneCode(id: "MD", name: "Moldova", flag: "🇲🇩", dialingCode: "+373"),
        CountryPhoneCode(id: "MC", name: "Monaco", flag: "🇲🇨", dialingCode: "+377"),
        CountryPhoneCode(id: "MN", name: "Mongolia", flag: "🇲🇳", dialingCode: "+976"),
        CountryPhoneCode(id: "ME", name: "Montenegro", flag: "🇲🇪", dialingCode: "+382"),
        CountryPhoneCode(id: "MA", name: "Morocco", flag: "🇲🇦", dialingCode: "+212"),
        CountryPhoneCode(id: "MZ", name: "Mozambique", flag: "🇲🇿", dialingCode: "+258"),
        CountryPhoneCode(id: "MM", name: "Myanmar", flag: "🇲🇲", dialingCode: "+95"),
        CountryPhoneCode(id: "NA", name: "Namibia", flag: "🇳🇦", dialingCode: "+264"),
        CountryPhoneCode(id: "NP", name: "Nepal", flag: "🇳🇵", dialingCode: "+977"),
        CountryPhoneCode(id: "NL", name: "Netherlands", flag: "🇳🇱", dialingCode: "+31"),
        CountryPhoneCode(id: "NZ", name: "New Zealand", flag: "🇳🇿", dialingCode: "+64"),
        CountryPhoneCode(id: "NI", name: "Nicaragua", flag: "🇳🇮", dialingCode: "+505"),
        CountryPhoneCode(id: "NE", name: "Niger", flag: "🇳🇪", dialingCode: "+227"),
        CountryPhoneCode(id: "NG", name: "Nigeria", flag: "🇳🇬", dialingCode: "+234"),
        CountryPhoneCode(id: "KP", name: "North Korea", flag: "🇰🇵", dialingCode: "+850"),
        CountryPhoneCode(id: "NO", name: "Norway", flag: "🇳🇴", dialingCode: "+47"),
        CountryPhoneCode(id: "OM", name: "Oman", flag: "🇴🇲", dialingCode: "+968"),
        CountryPhoneCode(id: "PK", name: "Pakistan", flag: "🇵🇰", dialingCode: "+92"),
        CountryPhoneCode(id: "PS", name: "Palestine", flag: "🇵🇸", dialingCode: "+970"),
        CountryPhoneCode(id: "PA", name: "Panama", flag: "🇵🇦", dialingCode: "+507"),
        CountryPhoneCode(id: "PG", name: "Papua New Guinea", flag: "🇵🇬", dialingCode: "+675"),
        CountryPhoneCode(id: "PY", name: "Paraguay", flag: "🇵🇾", dialingCode: "+595"),
        CountryPhoneCode(id: "PE", name: "Peru", flag: "🇵🇪", dialingCode: "+51"),
        CountryPhoneCode(id: "PH", name: "Philippines", flag: "🇵🇭", dialingCode: "+63"),
        CountryPhoneCode(id: "PL", name: "Poland", flag: "🇵🇱", dialingCode: "+48"),
        CountryPhoneCode(id: "PT", name: "Portugal", flag: "🇵🇹", dialingCode: "+351"),
        CountryPhoneCode(id: "PR", name: "Puerto Rico", flag: "🇵🇷", dialingCode: "+1939"),
        CountryPhoneCode(id: "QA", name: "Qatar", flag: "🇶🇦", dialingCode: "+974"),
        CountryPhoneCode(id: "RO", name: "Romania", flag: "🇷🇴", dialingCode: "+40"),
        CountryPhoneCode(id: "RU", name: "Russia", flag: "🇷🇺", dialingCode: "+7"),
        CountryPhoneCode(id: "RW", name: "Rwanda", flag: "🇷🇼", dialingCode: "+250"),
        CountryPhoneCode(id: "KN", name: "Saint Kitts and Nevis", flag: "🇰🇳", dialingCode: "+1869"),
        CountryPhoneCode(id: "LC", name: "Saint Lucia", flag: "🇱🇨", dialingCode: "+1758"),
        CountryPhoneCode(id: "VC", name: "Saint Vincent", flag: "🇻🇨", dialingCode: "+1784"),
        CountryPhoneCode(id: "WS", name: "Samoa", flag: "🇼🇸", dialingCode: "+685"),
        CountryPhoneCode(id: "SA", name: "Saudi Arabia", flag: "🇸🇦", dialingCode: "+966"),
        CountryPhoneCode(id: "SN", name: "Senegal", flag: "🇸🇳", dialingCode: "+221"),
        CountryPhoneCode(id: "RS", name: "Serbia", flag: "🇷🇸", dialingCode: "+381"),
        CountryPhoneCode(id: "SC", name: "Seychelles", flag: "🇸🇨", dialingCode: "+248"),
        CountryPhoneCode(id: "SL", name: "Sierra Leone", flag: "🇸🇱", dialingCode: "+232"),
        CountryPhoneCode(id: "SG", name: "Singapore", flag: "🇸🇬", dialingCode: "+65"),
        CountryPhoneCode(id: "SK", name: "Slovakia", flag: "🇸🇰", dialingCode: "+421"),
        CountryPhoneCode(id: "SI", name: "Slovenia", flag: "🇸🇮", dialingCode: "+386"),
        CountryPhoneCode(id: "SB", name: "Solomon Islands", flag: "🇸🇧", dialingCode: "+677"),
        CountryPhoneCode(id: "SO", name: "Somalia", flag: "🇸🇴", dialingCode: "+252"),
        CountryPhoneCode(id: "ZA", name: "South Africa", flag: "🇿🇦", dialingCode: "+27"),
        CountryPhoneCode(id: "KR", name: "South Korea", flag: "🇰🇷", dialingCode: "+82"),
        CountryPhoneCode(id: "SS", name: "South Sudan", flag: "🇸🇸", dialingCode: "+211"),
        CountryPhoneCode(id: "ES", name: "Spain", flag: "🇪🇸", dialingCode: "+34"),
        CountryPhoneCode(id: "LK", name: "Sri Lanka", flag: "🇱🇰", dialingCode: "+94"),
        CountryPhoneCode(id: "SD", name: "Sudan", flag: "🇸🇩", dialingCode: "+249"),
        CountryPhoneCode(id: "SR", name: "Suriname", flag: "🇸🇷", dialingCode: "+597"),
        CountryPhoneCode(id: "SE", name: "Sweden", flag: "🇸🇪", dialingCode: "+46"),
        CountryPhoneCode(id: "CH", name: "Switzerland", flag: "🇨🇭", dialingCode: "+41"),
        CountryPhoneCode(id: "SY", name: "Syria", flag: "🇸🇾", dialingCode: "+963"),
        CountryPhoneCode(id: "TW", name: "Taiwan", flag: "🇹🇼", dialingCode: "+886"),
        CountryPhoneCode(id: "TJ", name: "Tajikistan", flag: "🇹🇯", dialingCode: "+992"),
        CountryPhoneCode(id: "TZ", name: "Tanzania", flag: "🇹🇿", dialingCode: "+255"),
        CountryPhoneCode(id: "TH", name: "Thailand", flag: "🇹🇭", dialingCode: "+66"),
        CountryPhoneCode(id: "TG", name: "Togo", flag: "🇹🇬", dialingCode: "+228"),
        CountryPhoneCode(id: "TO", name: "Tonga", flag: "🇹🇴", dialingCode: "+676"),
        CountryPhoneCode(id: "TT", name: "Trinidad and Tobago", flag: "🇹🇹", dialingCode: "+1868"),
        CountryPhoneCode(id: "TN", name: "Tunisia", flag: "🇹🇳", dialingCode: "+216"),
        CountryPhoneCode(id: "TR", name: "Turkey", flag: "🇹🇷", dialingCode: "+90"),
        CountryPhoneCode(id: "TM", name: "Turkmenistan", flag: "🇹🇲", dialingCode: "+993"),
        CountryPhoneCode(id: "UG", name: "Uganda", flag: "🇺🇬", dialingCode: "+256"),
        CountryPhoneCode(id: "UA", name: "Ukraine", flag: "🇺🇦", dialingCode: "+380"),
        CountryPhoneCode(id: "AE", name: "United Arab Emirates", flag: "🇦🇪", dialingCode: "+971"),
        CountryPhoneCode(id: "GB", name: "United Kingdom", flag: "🇬🇧", dialingCode: "+44"),
        CountryPhoneCode(id: "US", name: "United States", flag: "🇺🇸", dialingCode: "+1"),
        CountryPhoneCode(id: "UY", name: "Uruguay", flag: "🇺🇾", dialingCode: "+598"),
        CountryPhoneCode(id: "UZ", name: "Uzbekistan", flag: "🇺🇿", dialingCode: "+998"),
        CountryPhoneCode(id: "VU", name: "Vanuatu", flag: "🇻🇺", dialingCode: "+678"),
        CountryPhoneCode(id: "VE", name: "Venezuela", flag: "🇻🇪", dialingCode: "+58"),
        CountryPhoneCode(id: "VN", name: "Vietnam", flag: "🇻🇳", dialingCode: "+84"),
        CountryPhoneCode(id: "YE", name: "Yemen", flag: "🇾🇪", dialingCode: "+967"),
        CountryPhoneCode(id: "ZM", name: "Zambia", flag: "🇿🇲", dialingCode: "+260"),
        CountryPhoneCode(id: "ZW", name: "Zimbabwe", flag: "🇿🇼", dialingCode: "+263"),
    ]
}
